# Import Libraries

In [45]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

# Scrape NBA Stats

Get url with 2018-2019 nba 3 point stats from Basketball Reference

In [2]:
headers = {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36'}
url  = 'https://www.basketball-reference.com/leagues/NBA_2019_totals.html#totals_stats::fg3'
response = requests.get(url, headers = headers, timeout=5)

Parse stats from Basketball Reference html into stats_list

In [42]:
stats_list = []
soup = BeautifulSoup(response.content, 'html.parser')
table = soup.find('table', {'id' : 'totals_stats'})
rows = table.find_all('tr', {'class': 'full_table'})
for row in rows:
    row_stats = []
    left = row.find_all('td', {'class': 'left'})
    row_stats.append(left[0].find('a').get_text())  
    if len(left[1].find_all('a')) > 0:
        row_stats.append(left[1].find('a').get_text())
    else:
        row_stats.append(left[1].get_text())
    right = row.find_all('td', {'class': 'right'})
    for datapoint in right:
        row_stats.append(datapoint.get_text())  
    center = row.find_all('td', {'class': 'center'})
    for datapoint in center:
        row_stats.append(datapoint.get_text()) 
    stats_list.append(row_stats)

Create df from stats_list

In [46]:
columns = ['Name', 'Team', 'Age', 'G', 'GS', 'MP', 'FG']
pd.DataFrame(stats_list)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,√Ålex Abrines,OKC,25,31,2,588,56,157,.357,41,...,5,43,48,20,17,6,14,53,165,SG
1,Quincy Acy,PHO,28,10,0,123,4,18,.222,2,...,3,22,25,8,1,4,4,24,17,PF
2,Jaylen Adams,ATL,22,34,1,428,38,110,.345,25,...,11,49,60,65,14,5,28,45,108,PG
3,Steven Adams,OKC,25,80,80,2669,481,809,.595,0,...,391,369,760,124,117,76,135,204,1108,C
4,Bam Adebayo,MIA,21,82,28,1913,280,486,.576,3,...,165,432,597,184,71,65,121,203,729,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,Trae Young,ATL,20,81,81,2503,525,1256,.418,156,...,64,237,301,653,72,15,308,140,1549,PG
526,Cody Zeller,CHO,26,49,47,1243,190,345,.551,6,...,110,223,333,102,38,41,62,164,497,C
527,Tyler Zeller,TOT,29,6,1,93,16,30,.533,0,...,11,13,24,4,1,3,4,20,46,C
528,Ante ≈Ωi≈æiƒá,CLE,22,59,25,1082,183,331,.553,0,...,108,212,320,53,13,22,61,113,459,C
529,Ivica Zubac,TOT,21,59,37,1040,212,379,.559,0,...,115,247,362,63,14,51,70,137,525,C